#!/bin/bash

wanIf=$(uci -q get indiochilli.smartap.hs_uplink_interface)
lanIf=$(uci -q get indiochilli.smartap.hs_downlink_interface)

if [[ $(uci get network.wan.proto) == pppoe ]]; then
	wanIf=pppoe-wan
fi

if [[ $(uci get indiochilli.smartap.chilli_bridge_mode) -eq 1 ]]; then
	wanIf=
	lanIf=

	for lan_dev in $(uci get indiochilli.smartap.lan_dev) $(ifconfig -a | egrep -o 'wlan-hs[0-9]+'); do
		lanIf="$lanIf $lan_dev"
	done

	for wan_dev in $(uci get indiochilli.smartap.hs_uplink_dev); do
		wanIf="$wanIf $wan_dev"
	done
fi

#First cleaning up tc class to support FUP requirement
#TODO: Support for SDWAN to be added
if [[ $WISPR_BANDWIDTH_MAX_DOWN -gt 0 ]]; then
	for lan_dev in $lanIf; do
		tc filter del dev $lan_dev prio $CLASS_ID
		tc class del dev $lan_dev classid 1:$CLASS_ID
	done
fi

if [[ $WISPR_BANDWIDTH_MAX_UP -gt 0 ]]; then
	for wan_dev in $wanIf; do
		tc filter del dev $wan_dev prio $CLASS_ID
		tc class del dev $wan_dev classid 2:$CLASS_ID
	done
fi


if [[ $WISPR_BANDWIDTH_MAX_DOWN -gt 0 ]]; then
	for lan_dev in $lanIf; do
		tc class add dev $lan_dev parent 1:1 classid 1:$CLASS_ID htb rate ${WISPR_BANDWIDTH_MAX_DOWN}bit ceil $((1 * WISPR_BANDWIDTH_MAX_DOWN))bit
		tc filter add dev $lan_dev protocol ip prio $CLASS_ID handle $FRAMED_IP_ADDRESS_HEX fw classid 1:$CLASS_ID
	done
fi

if [[ $WISPR_BANDWIDTH_MAX_UP -gt 0 ]]; then
	for wan_dev in $wanIf; do
		tc class add dev $wan_dev parent 2:1 classid 2:$CLASS_ID htb rate ${WISPR_BANDWIDTH_MAX_UP}bit ceil $((1 * WISPR_BANDWIDTH_MAX_UP))bit
		tc filter add dev $wan_dev protocol ip prio $CLASS_ID handle $FRAMED_IP_ADDRESS_HEX fw classid 2:$CLASS_ID
	done
fi
